version: '3.8'

services:
  deepspeech:
    image: deepspeech-image
    command: tail -f /dev/null
    volumes:
      - DeepSpeech-data:/DeepSpeech/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

volumes:
  DeepSpeech-data:
    name: DeepSpeech-data